# Generated by Django 4.1.4 on 2024-02-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(default='/images/avatar/1.png', null=True, upload_to='user_images'),
        ),
    ]
